// DBML Structure for more.com.live

Table event {
  event_id integer [primary key]
  group_code text [ref: > group.group_code]
  venue_id integer [ref: > venue.venue_id]
  duration integer
  producer_name text
}

Table venue {
  venue_id integer [primary key]
  venue_name text
  latitude float
  longitude float
}

Table group {
  group_code text [primary key]
  event_url text
  event_title text
  event_location text
  event_description text
  event_date text
  event_thumbnail_url text

}