// DBML Structure for more.com.live

Table mainPageEvent { // events from main page
  group_code text [primary key]
  url text
  title text
  date text
  thumbnail_url text 
} // this information is scraped by the get_active_urls.py script

Table event { // every event has its own page
  event_id integer [primary key]
  group_code text
  latitude float
  longitude float
  producer_name text
  duration integer
} // this information is in https://www.more.com/_api/playdetails/getevents?eventGroupCode={group_code}

Ref: event.group_code - mainPageEvent.group_code // 1-1
