name: Scrape more.com for events

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install pip requirements
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python get_active_urls.py > info.json
      - name: Upload info.json to compatible s3 service
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./info.json
          S3_PREFIX: public
          S3_ENDPOINT: ${{ secrets.TIGRIS_ENDPOINT_URL }}
          S3_BUCKET: ${{ secrets.TIGRIS_BUCKET_NAME }}
          S3_ACCESS_KEY_ID: ${{ secrets.TIGRIS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.TIGRIS_SECRET_ACCESS_KEY }}


